site_name: "Drehmal: APOTHEΩSIS Wiki"
site_description: "This is the official Wiki for Drehmal: APOTHEΩSIS."
site_url: https://wiki.drehmal.cyou
repo_url: https://github.com/drehmal/wiki
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.gif
  icon:
    repo: fontawesome/brands/github
    admonition: 
      abstract: fontawesome/solid/map-location
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - navigation.instant

plugins:
  # provided by MkDocs
  - search
  # provided by Material theme
  - tags:
      tags_file: Overview.md
  - social:
      cards: !ENV [CI, false]
  # provided by others
  - htmlproofer:
      enabled: !ENV [CI, false]
  - roamlinks
  - minify:
      minify_html: !ENV [CI, false]
      minify_js: !ENV [CI, false]
      minify_css: !ENV [CI, false]
  - glightbox
  - redirects:
        redirect_maps:
            # General
            'Achievements.md': 'Advancements.md'
            'Regions.md': 'World/Regions/index.md'
            'Settlements.md': 'World/Settlements/index.md'
            'Towers.md': 'World/Towers.md'
            # Merchants
            'acacia_merchant.md': 'World/Settlements/Athrah.md'
            'bamboo_merchant.md': 'World/Settlements/Firteid.md'
            'beetroot_merchant.md': 'World/Settlements/Fort_Nimahj.md'
            'berry_merchant.md': 'World/Settlements/Mossfield.md'
            'birch_merchant.md': 'World/Settlements/Dusps.md'
            'bone_dealer.md': 'World/Settlements/Highfall.md'
            'clay_merchant.md': 'World/Settlements/Fort_Nimahj.md'
            'chicken_merchant.md': 'World/Settlements/Gozak.md'
            'coal_merchant.md': 'World/Settlements/Drabyel.md'
            'cod_merchant.md': 'World/Settlements/Okeke.md'
            'concrete_merchant.md': 'World/Settlements/Ebonrun.md'
            'coral_merchant.md': 'World/Settlements/Mohta.md'
            'dark_oak_merchant.md': 'World/Settlements/Gozak.md'
            'dye_merchant.md': 'World/Settlements/Dusps.md'
            'exotic_fish_merchant.md': 'World/Settlements/Okeke.md'
            'glass_merchant.md': 'World/Settlements/New_Sahd.md'
            'glazed_terracotta_merchant.md': 'World/Settlements/Gozak.md'
            'gold_merchant.md': 'World/Settlements/Athrah.md'
            'gunpowder_merchant.md': 'World/Settlements/Ebonrun.md'
            'honey_merchant.md': 'World/Settlements/Dusps.md'
            'ice_merchant.md': 'World/Settlements/Highfall.md'
            'iron_merchant.md': 'World/Settlements/Ebonrun.md'
            'jungle_merchant.md': 'World/Settlements/Mohta.md'
            'kelp_merchant.md': 'World/Settlements/New_Sahd.md'
            'leather_merchant.md': 'World/Settlements/Highfall.md'
            'meat_merchant.md': 'World/Settlements/Mossfield.md'
            'melon_merchant.md': 'World/Settlements/Gozak.md'
            'oak_merchant.md': 'World/Settlements/Drabyel.md'
            'paper_merchant.md': 'World/Settlements/Tharxax_City.md'
            'pork_merchant.md': 'World/Settlements/Tharxax_City.md'
            'prismarine_merchant.md': 'World/Settlements/Firteid.md'
            'quartz_merchant.md': 'World/Settlements/New_Sahd.md'
            'rabbit_merchant.md': 'World/Settlements/Highfall.md'
            'redstone_merchant.md': 'World/Settlements/Tharxax_City.md'
            'salmon_merchant.md': 'World/Settlements/Mossfield.md'
            'slime_merchant.md': 'World/Settlements/Tharxax_City.md'
            'sponge_merchant.md': 'World/Settlements/Mohta.md'
            'spruce_merchant.md': 'World/Settlements/Mossfield.md'
            'string_merchant.md': 'World/Settlements/New_Sahd.md'
            'sugar_merchant.md': 'World/Settlements/Okeke.md'
            'terracotta_merchant.md': 'World/Settlements/Athrah.md'
            'volcano_merchant.md': 'World/Settlements/Firteid.md'
            'wheat_merchant.md': 'World/Settlements/Drabyel.md'
            'wool_merchant.md': 'World/Settlements/Fort_Nimahj.md'
            # Other
            'abandoned_troupemaster.md': 'World/Settlements/Highfall.md'
            'acillary_research_facility.md': "World/Points_of_Interest/Sal'Mevir.md"
            'terminus.md': "World/Points_of_Interest/The_Terminus.md"


markdown_extensions:
  - footnotes
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.snippets:
      base_path: include/
      #auto_append:
      #  - includes/abbreviations.md

extra:
  social:
    - icon: fontawesome/solid/dragon
      link: https://www.drehmal.net/
      name: "The Official Drehmal: APOTHEOSIS Web Page"
    - icon: fontawesome/brands/discord
      link: https://discord.drehmal.net/
      name: The Official Drehmal Discord
  generator: false
